const { createClient } = require('@libsql/client');
const path = require('path');
const fs = require('fs');
const https = require('https');

const isVercel = !!process.env.VERCEL;

const EXISTING_LOCAL_IMAGES = new Set([
  'aman_andom_001.jpg',
  'burari_deaths_001.jpg',
  'burari_deaths_001_1782152849860.jpg',
  'burari_diary.jpg',
  'burari_family.jpg',
  'cia_mk_ultra_program.jpg',
  'daily_dossier.jpg',
  'facundo_astudillo_castro_001.jpg',
  'fakhraddin_aboszoda_001.jpg',
  'pipes_toi.jpg',
  'said_s_bedair_001.jpg',
  'the_asch_conformity_experiments.jpg',
  'the_dyatlov_pass_incident.jpg',
  'the_philadelphia_experiment.jpg',
  'unit_731_experiments.jpg',
  'uwe_barschel_001.jpg'
]);

// Load the image manifest generated by generate_stories_ai.cjs after each run.
// This is the ground-truth list of filenames actually committed to the git repo.
let _imageManifestSet = null;
function getImageManifest() {
  if (_imageManifestSet !== null) return _imageManifestSet;
  try {
    const manifestPath = path.join(__dirname, 'public', 'content', 'image_manifest.json');
    const data = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
    _imageManifestSet = new Set(Array.isArray(data.committed) ? data.committed : []);
  } catch {
    // manifest not yet generated (first run), treat as empty
    _imageManifestSet = new Set();
  }
  return _imageManifestSet;
}

// Returns true if a /content/images/<filename> path is considered valid on this environment.
function isLocalImageValid(filename) {
  if (EXISTING_LOCAL_IMAGES.has(filename)) return true;
  if (getImageManifest().has(filename)) return true;
  // On non-Vercel (local dev), also check the filesystem directly
  if (!isVercel) {
    const absolutePath = path.join(__dirname, 'public', 'content', 'images', filename);
    return fs.existsSync(absolutePath);
  }
  return false; // Vercel: file not in manifest → treat as missing
}

const databaseUrl = process.env.TURSO_DATABASE_URL || 'file:lore.db';
const authToken = process.env.TURSO_AUTH_TOKEN || '';

const client = createClient({
  url: databaseUrl,
  authToken: authToken
});

let isInitialized = false;

async function ensureInit() {
  if (isInitialized) return;

  await client.executeMultiple(`
    CREATE TABLE IF NOT EXISTS stories (
      story_id TEXT PRIMARY KEY,
      title TEXT,
      category TEXT,
      hook TEXT,
      concepts TEXT,
      severity TEXT,
      hero_image TEXT,
      added_date TEXT,
      draft INTEGER DEFAULT 0,
      reactions TEXT,
      evidence_links TEXT,
      connections TEXT,
      layers TEXT,
      custom_image_prompt TEXT,
      vocabulary TEXT,
      year TEXT
    );

    CREATE TABLE IF NOT EXISTS recommendations (
      id TEXT PRIMARY KEY,
      topic TEXT,
      date TEXT,
      status TEXT
    );

    CREATE TABLE IF NOT EXISTS feedback (
      id TEXT PRIMARY KEY,
      rating INTEGER,
      tags TEXT,
      note TEXT,
      timestamp TEXT,
      page TEXT,
      addressed INTEGER DEFAULT 0
    );

    CREATE TABLE IF NOT EXISTS daily_reactions (
      date TEXT PRIMARY KEY,
      likes INTEGER DEFAULT 0,
      gripping INTEGER DEFAULT 0,
      scared INTEGER DEFAULT 0,
      mindblown INTEGER DEFAULT 0
    );

    CREATE TABLE IF NOT EXISTS pageviews (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      visitor_id TEXT,
      session_id TEXT,
      path TEXT,
      referrer TEXT,
      user_agent TEXT,
      timestamp TEXT,
      ip TEXT,
      city TEXT,
      region TEXT,
      country TEXT,
      country_code TEXT,
      org TEXT
    );

    CREATE TABLE IF NOT EXISTS comments (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      target_id TEXT,
      username TEXT,
      comment TEXT,
      timestamp TEXT
    );

    CREATE TABLE IF NOT EXISTS daily_dossier (
      date TEXT PRIMARY KEY,
      story_id TEXT
    );
  `);

  // Try to alter pageviews table if it was created without geolocation columns
  try { await client.execute("ALTER TABLE pageviews ADD COLUMN ip TEXT"); } catch(e){}
  try { await client.execute("ALTER TABLE pageviews ADD COLUMN city TEXT"); } catch(e){}
  try { await client.execute("ALTER TABLE pageviews ADD COLUMN region TEXT"); } catch(e){}
  try { await client.execute("ALTER TABLE pageviews ADD COLUMN country TEXT"); } catch(e){}
  try { await client.execute("ALTER TABLE pageviews ADD COLUMN country_code TEXT"); } catch(e){}
  try { await client.execute("ALTER TABLE pageviews ADD COLUMN org TEXT"); } catch(e){}
  try { await client.execute("ALTER TABLE stories ADD COLUMN custom_image_prompt TEXT"); } catch(e){}
  try { await client.execute("ALTER TABLE stories ADD COLUMN vocabulary TEXT"); } catch(e){}
  try { await client.execute("ALTER TABLE stories ADD COLUMN year TEXT"); } catch(e){}

  isInitialized = true;
}

async function ensureStoryReactions(story) {
  const rx = story.reactions || {};
  const total = (rx.like || 0) + (rx.gripping || 0) + (rx.scared || 0) + (rx.mindblown || 0);
  if (total > 0) return rx;

  const hash = (story.title || '').split('').reduce((acc, char) => acc + char.charCodeAt(0), 0) + (story.story_id || '').length;
  const category = story.category || '';
  const severity = story.severity || '';

  const seeded = {
    like: 12 + (hash % 45),
    gripping: 10 + (hash % 35),
    scared: (category === 'paranormal' || category === 'true_crime' || severity === 'extreme') ? 22 + (hash % 50) : 1 + (hash % 6),
    mindblown: (category === 'psychology' || category === 'conspiracy') ? 25 + (hash % 55) : 3 + (hash % 10)
  };

  try {
    await client.execute({
      sql: 'UPDATE stories SET reactions = ? WHERE story_id = ?',
      args: [JSON.stringify(seeded), story.story_id]
    });
  } catch (err) {
    console.warn(`[DB Reactions] Failed to save seeded reactions for story ${story.story_id}:`, err.message);
  }

  return seeded;
}

async function getStories(includeDrafts = false, includeFullContent = false) {
  await ensureInit();
  const sql = includeDrafts 
    ? 'SELECT * FROM stories' 
    : 'SELECT * FROM stories WHERE draft = 0';
  
  const res = await client.execute(sql);
  const rows = res.rows;
  const formatted = [];
  
  for (const row of rows) {
    let isImageMissingOnServer = false;
    const img = row.hero_image;
    if (!img || img === 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=800') {
      isImageMissingOnServer = true;
    } else if (img.startsWith('/content/images/')) {
      const filename = img.substring('/content/images/'.length);
      if (!isLocalImageValid(filename)) {
        isImageMissingOnServer = true;
      }
    }
    // Note: remote https:// URLs are trusted as-is (frontend will handle 404 via onError)

    const s = {
      story_id: row.story_id,
      title: row.title,
      category: row.category,
      hook: row.hook,
      concepts: JSON.parse(row.concepts || '[]'),
      severity: row.severity,
      hero_image: row.hero_image,
      added_date: row.added_date,
      draft: !!row.draft,
      reactions: JSON.parse(row.reactions || '{}'),
      year: row.year || 'N/A',
      image_missing: isImageMissingOnServer
    };
    if (includeFullContent) {
      s.evidence_links = JSON.parse(row.evidence_links || '[]');
      s.connections = JSON.parse(row.connections || '[]');
      s.layers = JSON.parse(row.layers || '[]');
      s.vocabulary = JSON.parse(row.vocabulary || '{}');
    }
    s.reactions = await ensureStoryReactions(s);
    if (s.added_date) {
      s.added_date = s.added_date.substring(0, 10);
    } else {
      const hash = (s.story_id || '').split('').reduce((a, c) => a + c.charCodeAt(0), 0);
      const base = new Date('2026-01-01').getTime();
      const spreadDays = hash % 180;
      s.added_date = new Date(base + (spreadDays * 24 * 60 * 60 * 1000)).toISOString().split('T')[0];
    }
    formatted.push(s);
  }
  return formatted;
}

async function getStory(story_id) {
  await ensureInit();
  const res = await client.execute({
    sql: 'SELECT * FROM stories WHERE story_id = ?',
    args: [story_id]
  });
  const row = res.rows[0];
  if (!row) return null;

  let isImageMissingOnServer = false;
  const img = row.hero_image;
  if (!img || img === 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=800') {
    isImageMissingOnServer = true;
  } else if (img.startsWith('/content/images/')) {
    const filename = img.substring('/content/images/'.length);
    if (!isLocalImageValid(filename)) {
      isImageMissingOnServer = true;
    }
  }

  const s = {
    ...row,
    draft: !!row.draft,
    concepts: JSON.parse(row.concepts || '[]'),
    reactions: JSON.parse(row.reactions || '{}'),
    evidence_links: JSON.parse(row.evidence_links || '[]'),
    connections: JSON.parse(row.connections || '[]'),
    layers: JSON.parse(row.layers || '[]'),
    vocabulary: JSON.parse(row.vocabulary || '{}'),
    year: row.year || 'N/A',
    image_missing: isImageMissingOnServer
  };
  s.reactions = await ensureStoryReactions(s);
  if (s.added_date) {
    s.added_date = s.added_date.substring(0, 10);
  } else {
    const hash = (s.story_id || '').split('').reduce((a, c) => a + c.charCodeAt(0), 0);
    const base = new Date('2026-01-01').getTime();
    const spreadDays = hash % 180;
    s.added_date = new Date(base + (spreadDays * 24 * 60 * 60 * 1000)).toISOString().split('T')[0];
  }
  return s;
}

async function insertStory(story) {
  await ensureInit();
  await client.execute({
    sql: `INSERT OR REPLACE INTO stories (
      story_id, title, category, hook, concepts, severity, hero_image, added_date, draft, reactions, evidence_links, connections, layers, custom_image_prompt, vocabulary, year
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    args: [
      story.story_id,
      story.title,
      story.category,
      story.hook,
      JSON.stringify(story.concepts || []),
      story.severity,
      story.hero_image || null,
      story.added_date || new Date().toLocaleDateString('en-CA'),
      story.draft ? 1 : 0,
      JSON.stringify(story.reactions || { gripping: 0, scared: 0, mindblown: 0, like: 0 }),
      JSON.stringify(story.evidence_links || []),
      JSON.stringify(story.connections || []),
      JSON.stringify(story.layers || []),
      story.custom_image_prompt || null,
      JSON.stringify(story.vocabulary || {}),
      story.year || 'N/A'
    ]
  });
  return await getStory(story.story_id);
}

async function updateStory(story_id, updates) {
  const existing = await getStory(story_id);
  if (!existing) return false;
  
  const today = new Date().toLocaleDateString('en-CA');
  if (updates.hero_image && (!existing.added_date || existing.added_date === '2026-01-01')) {
    updates.added_date = today;
  }
  
  const merged = { ...existing, ...updates };
  await insertStory(merged);
  return true;
}

async function deleteStory(story_id) {
  await ensureInit();
  if (!story_id || story_id === 'undefined' || story_id === 'null' || story_id === '') {
    await client.execute("DELETE FROM stories WHERE story_id IS NULL OR story_id = '' OR story_id = 'undefined' OR story_id = 'null'");
  } else {
    await client.execute({
      sql: 'DELETE FROM stories WHERE story_id = ?',
      args: [story_id]
    });
  }
}

function hasProperThumbnail(story) {
  if (!story || !story.hero_image) return false;
  const img = story.hero_image;
  if (img === 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=800') return false;
  return img.startsWith('http') || img.startsWith('/') || img.startsWith('data:') || img === 'typography';
}

async function publishStory(story_id) {
  const story = await getStory(story_id);
  if (!story) return false;
  if (!hasProperThumbnail(story)) {
    throw new Error('Story lacks a proper thumbnail image.');
  }
  
  const today = new Date().toLocaleDateString('en-CA');
  const currentDate = (!story.added_date || story.added_date === '2026-01-01' || story.draft) ? today : story.added_date;
  await client.execute({
    sql: 'UPDATE stories SET draft = 0, added_date = ? WHERE story_id = ?',
    args: [currentDate, story_id]
  });
  
  await exportStoriesToJSON();
  return true;
}

async function publishAllStories() {
  await ensureInit();
  const res = await client.execute('SELECT * FROM stories WHERE draft = 1');
  const drafts = res.rows;
  let count = 0;
  
  const batchStmts = [];
  const today = new Date().toLocaleDateString('en-CA');
  
  for (const row of drafts) {
    const s = {
      ...row,
      concepts: JSON.parse(row.concepts || '[]'),
      reactions: JSON.parse(row.reactions || '{}'),
      evidence_links: JSON.parse(row.evidence_links || '[]'),
      connections: JSON.parse(row.connections || '[]'),
      layers: JSON.parse(row.layers || '[]')
    };
    if (hasProperThumbnail(s)) {
      const currentDate = (!s.added_date || s.added_date === '2026-01-01' || s.draft) ? today : s.added_date;
      batchStmts.push({
        sql: 'UPDATE stories SET draft = 0, added_date = ? WHERE story_id = ?',
        args: [currentDate, s.story_id]
      });
      count++;
    }
  }
  
  if (batchStmts.length > 0) {
    await client.batch(batchStmts, "write");
    await exportStoriesToJSON();
  }
  return count;
}

async function getRecommendations() {
  await ensureInit();
  const res = await client.execute('SELECT * FROM recommendations ORDER BY date DESC');
  return res.rows.map(r => ({ ...r }));
}

async function insertRecommendation(rec) {
  await ensureInit();
  await client.execute({
    sql: 'INSERT OR REPLACE INTO recommendations (id, topic, date, status) VALUES (?, ?, ?, ?)',
    args: [rec.id, rec.topic, rec.date, rec.status || 'pending']
  });
}

async function deleteRecommendation(id) {
  await ensureInit();
  await client.execute({
    sql: 'DELETE FROM recommendations WHERE id = ?',
    args: [id]
  });
}

async function updateRecommendationStatus(id, status) {
  await ensureInit();
  await client.execute({
    sql: 'UPDATE recommendations SET status = ? WHERE id = ?',
    args: [status, id]
  });
}

async function getFeedback() {
  await ensureInit();
  const res = await client.execute('SELECT * FROM feedback ORDER BY timestamp DESC');
  return res.rows.map(row => ({
    ...row,
    tags: JSON.parse(row.tags || '[]'),
    addressed: !!row.addressed
  }));
}

async function insertFeedback(fb) {
  await ensureInit();
  await client.execute({
    sql: 'INSERT OR REPLACE INTO feedback (id, rating, tags, note, timestamp, page, addressed) VALUES (?, ?, ?, ?, ?, ?, ?)',
    args: [
      fb.id,
      fb.rating,
      JSON.stringify(fb.tags || []),
      fb.note || '',
      fb.timestamp || new Date().toISOString(),
      fb.page || '/',
      fb.addressed ? 1 : 0
    ]
  });
}

async function checkDuplicate(topic) {
  await ensureInit();
  const topicLower = topic.trim().toLowerCase();
  
  const resStories = await client.execute('SELECT story_id, title FROM stories');
  const storiesList = resStories.rows;
  const storyDup = storiesList.find(s => {
    const titleLower = s.title.toLowerCase();
    return titleLower === topicLower || titleLower.includes(topicLower) || topicLower.includes(titleLower);
  });
  if (storyDup) return true;

  const resRecs = await client.execute('SELECT topic FROM recommendations');
  const recsList = resRecs.rows;
  const recDup = recsList.find(r => {
    const rTopicLower = r.topic.toLowerCase();
    return rTopicLower === topicLower || rTopicLower.includes(topicLower) || topicLower.includes(rTopicLower);
  });
  if (recDup) return true;

  return false;
}

async function deleteFeedback(id) {
  await ensureInit();
  await client.execute({
    sql: 'DELETE FROM feedback WHERE id = ?',
    args: [id]
  });
}

async function updateFeedbackAddressed(id, addressed) {
  await ensureInit();
  await client.execute({
    sql: 'UPDATE feedback SET addressed = ? WHERE id = ?',
    args: [addressed ? 1 : 0, id]
  });
}

async function exportStoriesToJSON() {
  if (isVercel) {
    console.log('[DB] Running on Vercel. Skipping static file export (GitHub Sync should be used for persistence).');
    return;
  }
  const STORIES_FILE = path.join(__dirname, 'public', 'content', 'stories.json');
  const CONCEPTS_FILE = path.join(__dirname, 'public', 'content', 'concept_index.json');
  const STORIES_DIR = path.join(__dirname, 'public', 'content', 'stories');
  
  if (!fs.existsSync(STORIES_DIR)) {
    fs.mkdirSync(STORIES_DIR, { recursive: true });
  }

  // 1. Export metadata list (includeFullContent = false)
  const metadataStories = await getStories(false, false);
  
  // 2. Export full stories (includeFullContent = true) to individual files
  const fullStoriesList = await getStories(false, true);

  try {
    fs.writeFileSync(STORIES_FILE, JSON.stringify({ stories: metadataStories }, null, 2));
    
    for (const story of fullStoriesList) {
      const storyFile = path.join(STORIES_DIR, `${story.story_id}.json`);
      fs.writeFileSync(storyFile, JSON.stringify(story, null, 2));
    }
    
    const conceptIndex = {};
    metadataStories.forEach(story => {
      if (story.concepts) {
        story.concepts.forEach(concept => {
          const c = concept.trim().toLowerCase();
          if (!conceptIndex[c]) {
            conceptIndex[c] = [];
          }
          if (!conceptIndex[c].includes(story.story_id)) {
            conceptIndex[c].push(story.story_id);
          }
        });
      }
    });
    fs.writeFileSync(CONCEPTS_FILE, JSON.stringify(conceptIndex, null, 2));
    console.log(`[DB] Successfully exported ${metadataStories.length} live story metadata entries and individual story JSONs.`);
  } catch (err) {
    console.error('[DB] Failed to export stories to static JSON files:', err.message);
  }
}

function fetchGitHubStoriesJson() {
  return new Promise((resolve, reject) => {
    const url = 'https://raw.githubusercontent.com/Mr-Hkds/LORE/main/public/content/stories.json';
    https.get(url, { headers: { 'User-Agent': 'SevenDescents/2.0' }, timeout: 5000 }, (res) => {
      if (res.statusCode !== 200) {
        return reject(new Error(`HTTP ${res.statusCode}`));
      }
      let body = '';
      res.on('data', chunk => body += chunk);
      res.on('end', () => {
        try {
          resolve(JSON.parse(body));
        } catch (e) {
          reject(e);
        }
      });
    }).on('error', reject);
  });
}

async function seed() {
  await ensureInit();
  
  const STORIES_FILE = path.join(__dirname, 'public', 'content', 'stories.json');
  const RECOMMENDATIONS_FILE = path.join(__dirname, 'public', 'content', 'recommendations.json');
  const FEEDBACK_FILE = path.join(__dirname, 'public', 'content', 'feedback.json');

  let data = null;
  // Try fetching raw stories.json from GitHub first to incorporate skips immediately
  try {
    console.log('[DB SEED] Attempting to fetch seed data from GitHub raw URL...');
    data = await fetchGitHubStoriesJson();
    console.log('[DB SEED] Successfully fetched seed data from GitHub.');
  } catch (ghErr) {
    console.warn('[DB SEED] GitHub raw fetch failed, falling back to local file:', ghErr.message);
    try {
      data = require('./public/content/stories.json');
    } catch (err) {
      if (fs.existsSync(STORIES_FILE)) {
        data = JSON.parse(fs.readFileSync(STORIES_FILE, 'utf8'));
      }
    }
  }
  const resStoriesCount = await client.execute('SELECT COUNT(*) as count FROM stories');
  const dbStoriesCount = resStoriesCount.rows[0]?.count || 0;

  if (data && Array.isArray(data.stories)) {
    try {
      const validStories = data.stories.filter(s => s && s.story_id && s.story_id !== 'null' && s.story_id !== 'undefined');
      const isInitialSeed = dbStoriesCount === 0;
      if (isInitialSeed) {
        console.log(`Database is empty. Initializing with ${validStories.length} stories from stories.json...`);
      } else {
        console.log(`Database already has ${dbStoriesCount} stories. Running incremental check (INSERT OR IGNORE)...`);
      }

      const batchStmts = validStories.map(s => ({
        sql: `${isInitialSeed ? 'INSERT OR REPLACE' : 'INSERT OR IGNORE'} INTO stories (
          story_id, title, category, hook, concepts, severity, hero_image, added_date, draft, reactions, evidence_links, connections, layers, vocabulary, year
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        args: [
          s.story_id || null,
          s.title || null,
          s.category || null,
          s.hook || null,
          JSON.stringify(s.concepts || []),
          s.severity || null,
          s.hero_image || null,
          s.added_date || null,
          s.draft ? 1 : 0,
          JSON.stringify(s.reactions || { gripping: 0, scared: 0, mindblown: 0, like: 0 }),
          JSON.stringify(s.evidence_links || []),
          JSON.stringify(s.connections || []),
          JSON.stringify(s.layers || []),
          JSON.stringify(s.vocabulary || {}),
          s.year || 'N/A'
        ]
      }));

      // Delete any extra stories from database ONLY if this is the initial seed alignment
      if (isInitialSeed) {
        const idsInJson = validStories.map(s => s.story_id);
        if (idsInJson.length > 0) {
          const placeholders = idsInJson.map(() => '?').join(',');
          batchStmts.push({
            sql: `DELETE FROM stories WHERE story_id NOT IN (${placeholders})`,
            args: idsInJson
          });
        } else {
          batchStmts.push({
            sql: `DELETE FROM stories`,
            args: []
          });
        }
      }

      await client.batch(batchStmts, "write");
      console.log(`Database stories alignment complete.`);
    } catch (e) {
      console.error('Failed to align stories in database:', e);
    }
  }

  const resRecCount = await client.execute('SELECT COUNT(*) as count FROM recommendations');
  const recCount = resRecCount.rows[0]?.count || 0;
  if (recCount === 0) {
    try {
      let recs = null;
      try {
        recs = require('./public/content/recommendations.json');
      } catch (err) {
        if (fs.existsSync(RECOMMENDATIONS_FILE)) {
          recs = JSON.parse(fs.readFileSync(RECOMMENDATIONS_FILE, 'utf8'));
        }
      }

      if (Array.isArray(recs)) {
        console.log(`Seeding ${recs.length} recommendations to database...`);
        const batchStmts = recs.map(r => ({
          sql: 'INSERT INTO recommendations (id, topic, date, status) VALUES (?, ?, ?, ?)',
          args: [r.id, r.topic, r.date, r.status || 'pending']
        }));
        await client.batch(batchStmts, "write");
      }
    } catch (e) {
      console.error('Failed to seed recommendations:', e);
    }
  }

  const resFbCount = await client.execute('SELECT COUNT(*) as count FROM feedback');
  const fbCount = resFbCount.rows[0]?.count || 0;
  if (fbCount === 0) {
    try {
      let feedback = null;
      try {
        feedback = require('./public/content/feedback.json');
      } catch (err) {
        if (fs.existsSync(FEEDBACK_FILE)) {
          feedback = JSON.parse(fs.readFileSync(FEEDBACK_FILE, 'utf8'));
        }
      }

      if (Array.isArray(feedback)) {
        console.log(`Seeding ${feedback.length} feedback entries to database...`);
        const batchStmts = feedback.map(f => ({
          sql: 'INSERT INTO feedback (id, rating, tags, note, timestamp, page, addressed) VALUES (?, ?, ?, ?, ?, ?, ?)',
          args: [
            f.id,
            f.rating,
            JSON.stringify(f.tags || []),
            f.note || '',
            f.timestamp || new Date().toISOString(),
            f.page || '/',
            f.addressed ? 1 : 0
          ]
        }));
        await client.batch(batchStmts, "write");
      }
    } catch (e) {
      console.error('Failed to seed feedback:', e);
    }
  }
}

async function getDailyReactions(date) {
  await ensureInit();
  const res = await client.execute({
    sql: 'SELECT * FROM daily_reactions WHERE date = ?',
    args: [date]
  });
  const row = res.rows[0];
  if (!row) return { intriguing: 0, gripping: 0, chilling: 0, mind_blowing: 0 };
  return {
    intriguing: row.likes || 0,
    gripping: row.gripping || 0,
    chilling: row.scared || 0,
    mind_blowing: row.mindblown || 0
  };
}

async function updateDailyReaction(date, reaction_type, undo = false) {
  await ensureInit();
  let colName = reaction_type;
  if (reaction_type === 'intriguing' || reaction_type === 'like') colName = 'likes';
  if (reaction_type === 'chilling' || reaction_type === 'scared') colName = 'scared';
  if (reaction_type === 'mind_blowing' || reaction_type === 'mindblown') colName = 'mindblown';

  if (!['likes', 'gripping', 'scared', 'mindblown'].includes(colName)) return false;

  await client.execute({
    sql: 'INSERT OR IGNORE INTO daily_reactions (date) VALUES (?)',
    args: [date]
  });
  const change = undo ? -1 : 1;
  await client.execute({
    sql: `UPDATE daily_reactions SET ${colName} = MAX(0, COALESCE(${colName}, 0) + ?) WHERE date = ?`,
    args: [change, date]
  });
  return true;
}

async function setDailyReactions(date, reactions) {
  await ensureInit();
  await client.execute({
    sql: `INSERT OR REPLACE INTO daily_reactions (date, likes, gripping, scared, mindblown)
          VALUES (?, ?, ?, ?, ?)`,
    args: [
      date,
      reactions.intriguing || reactions.likes || 0,
      reactions.gripping || 0,
      reactions.chilling || reactions.scared || 0,
      reactions.mind_blowing || reactions.mindblown || 0
    ]
  });
}

async function logPageView(pv) {
  // Disabled to save database API requests
}

async function getAnalyticsSummary() {
  // Disabled to save database API requests
  return {
    totalPageviews: 0,
    uniqueVisitors: 0,
    activeSessions: 0,
    recentPageviews: []
  };
}

async function getDailyDossierStoryId(date) {
  await ensureInit();
  const res = await client.execute({
    sql: 'SELECT story_id FROM daily_dossier WHERE date = ?',
    args: [date]
  });
  const row = res.rows[0];
  return row ? row.story_id : null;
}

async function setDailyDossierStoryId(date, story_id) {
  await ensureInit();
  await client.execute({
    sql: 'INSERT OR REPLACE INTO daily_dossier (date, story_id) VALUES (?, ?)',
    args: [date, story_id]
  });
}

seed().catch(err => console.error('[DB Seed] Failed to seed database:', err));

module.exports = {
  client,
  getStories,
  getStory,
  insertStory,
  updateStory,
  deleteStory,
  publishStory,
  publishAllStories,
  getRecommendations,
  insertRecommendation,
  deleteRecommendation,
  updateRecommendationStatus,
  getFeedback,
  insertFeedback,
  deleteFeedback,
  updateFeedbackAddressed,
  exportStoriesToJSON,
  checkDuplicate,
  getDailyReactions,
  updateDailyReaction,
  setDailyReactions,
  logPageView,
  getAnalyticsSummary,
  getDailyDossierStoryId,
  setDailyDossierStoryId
};
